# Generated by Django 3.2 on 2022-02-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220222_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='paid',
        ),
    ]
