# Generated by Django 3.2 on 2022-02-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='buyer',
            new_name='user',
        ),
    ]
