# Generated by Django 3.2 on 2022-02-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_buyer_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='mount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
