# Generated by Django 3.2 on 2022-02-23 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220222_0241'),
        ('cart', '0006_cart_mount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='mount',
            new_name='total_moun',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
